### ISSUE TITLE
CEM implementation

### ISSUE THREAD

**Issue by NoviceCrom** [Caojunxu/AC-FPN#5] opened 2020-09-07 07:55 UTC
Can not find CEM part in detectron/modeling/FPN.py, could you point out where it is?

**Comment by Caojunxu** [comment] 2020-09-07 09:24
Here https://github.com/Caojunxu/AC-FPN/blob/master/detectron/modeling/FPN.py#L354

**Comment by byfate** [comment] 2020-12-08 15:21
> Here https://github.com/Caojunxu/AC-FPN/blob/master/detectron/modeling/FPN.py#L354

hi nice work,I am wondering if the detectron implementation use dcn ,the paper mentioned,but i cannot find in fpn.py using dcn，also i cann't find it in the paper's graph too.And I want to ask if the CEM only used in p5?appreciated if you can reply.

**Comment by Caojunxu** [comment] 2020-12-10 06:49
Duplicate of #8

**Closed as completed by Caojunxu** 2020-12-10 06:49 UTC
