### ISSUE TITLE
Implementation of CEM

### ISSUE THREAD

**Issue by anonymoussss** [Caojunxu/AC-FPN#6] opened 2020-09-10 07:46 UTC
Hi,
I have been trying to reproduce your paper using mmdetection,  I refer to this repository and the version of paddlepaddle implemented by others. but when using the 1x learning schedule, the AP performance of Faster R-CNN w/Res50 has not been able to reach 38.5 (baseline is 37.4). I would like to ask, in the implementation of the CEM, what are the differences between it and DenseASPP besides Group Normalization?（I’m sorry I didn’t see the deformable convolution mentioned in the paper. Could you please point me?）

**Comment by byfate** [comment] 2020-12-08 15:18
> Hi,
> I have been trying to reproduce your paper using mmdetection, I refer to this repository and the version of paddlepaddle implemented by others. but when using the 1x learning schedule, the AP performance of Faster R-CNN w/Res50 has not been able to reach 38.5 (baseline is 37.4). I would like to ask, in the implementation of the CEM, what are the differences between it and DenseASPP besides Group Normalization?（I’m sorry I didn’t see the deformable convolution mentioned in the paper. Could you please point me?）

didn't see the dcn too,hope the author could reply,3q

**Comment by Caojunxu** [comment] 2020-12-10 06:49
Duplicate of #8

**Closed as completed by Caojunxu** 2020-12-10 06:49 UTC
